-- Coordinated cutover: old app and worker must be stopped. Reconcile every
-- delivery field before changing authority; the runner commits the ledger too.
DO $$
DECLARE snapshot jsonb;
BEGIN
  SELECT state INTO snapshot FROM cvg_runtime_state WHERE id = 1 FOR UPDATE;
  IF snapshot IS NOT NULL THEN
    IF jsonb_typeof(snapshot->'outbox') IS DISTINCT FROM 'array' THEN
      RAISE EXCEPTION 'OUTBOX_CUTOVER_INVALID_SNAPSHOT';
    END IF;
    IF EXISTS (SELECT 1 FROM jsonb_array_elements(snapshot->'outbox') message WHERE NULLIF(message->>'id', '') IS NULL)
       OR (SELECT count(*) <> count(DISTINCT message->>'id') FROM jsonb_array_elements(snapshot->'outbox') message) THEN
      RAISE EXCEPTION 'OUTBOX_CUTOVER_DUPLICATE_OR_MISSING_ID';
    END IF;
    CREATE TEMP TABLE outbox_cutover_source ON COMMIT DROP AS
      SELECT id, "eventType" AS event_type, "aggregateType" AS aggregate_type, "aggregateId" AS aggregate_id, payload,
        COALESCE("consumerType", CASE WHEN NULLIF(btrim(payload->>'notificationId'), '') IS NOT NULL
          OR "eventType" IN ('ResultReleased', 'ResultVoided', 'RecollectionRequested') THEN 'NOTIFICATION_DELIVERY' ELSE 'DOMAIN_EVENT' END) AS consumer_type,
        COALESCE("routingKey", CASE WHEN COALESCE("consumerType", CASE WHEN NULLIF(btrim(payload->>'notificationId'), '') IS NOT NULL
          OR "eventType" IN ('ResultReleased', 'ResultVoided', 'RecollectionRequested') THEN 'NOTIFICATION_DELIVERY' ELSE 'DOMAIN_EVENT' END) = 'NOTIFICATION_DELIVERY'
          THEN 'notification.in_app' ELSE 'domain.' || "eventType" END) AS routing_key,
        status, attempts, "availableAt" AS available_at, "correlationId" AS correlation_id, "lockedAt" AS locked_at,
        "workerId" AS worker_id, "claimToken" AS claim_token, "lastError" AS last_error, "deadLetteredAt" AS dead_lettered_at,
        "discardedAt" AS discarded_at, "discardedBy" AS discarded_by, "discardReason" AS discard_reason
      FROM jsonb_to_recordset(snapshot->'outbox') AS message (id text, "eventType" text, "aggregateType" text, "aggregateId" text,
        payload jsonb, "consumerType" text, "routingKey" text, status text, attempts integer, "availableAt" timestamptz,
        "correlationId" text, "lockedAt" timestamptz, "workerId" text, "claimToken" text, "lastError" text,
        "deadLetteredAt" timestamptz, "discardedAt" timestamptz, "discardedBy" text, "discardReason" text);
    IF EXISTS (SELECT 1 FROM outbox_cutover_source source JOIN outbox_messages persisted USING (id)
      WHERE ROW(persisted.event_type, persisted.aggregate_type, persisted.aggregate_id, persisted.payload,
        persisted.consumer_type, persisted.routing_key, persisted.status, persisted.attempts, persisted.available_at,
        persisted.correlation_id, persisted.locked_at, persisted.worker_id, persisted.claim_token, persisted.last_error,
        persisted.dead_lettered_at, persisted.discarded_at, persisted.discarded_by, persisted.discard_reason)
      IS DISTINCT FROM ROW(source.event_type, source.aggregate_type, source.aggregate_id, source.payload,
        source.consumer_type, source.routing_key, source.status, source.attempts, source.available_at,
        source.correlation_id, source.locked_at, source.worker_id, source.claim_token, source.last_error,
        source.dead_lettered_at, source.discarded_at, source.discarded_by, source.discard_reason)) THEN
      RAISE EXCEPTION 'OUTBOX_CUTOVER_PROJECTION_DIVERGED';
    END IF;
    INSERT INTO outbox_messages (id, event_type, aggregate_type, aggregate_id, payload, consumer_type, routing_key,
      status, attempts, available_at, correlation_id, locked_at, worker_id, claim_token, last_error,
      dead_lettered_at, discarded_at, discarded_by, discard_reason)
      SELECT * FROM outbox_cutover_source ON CONFLICT (id) DO NOTHING;
  END IF;
END $$;

ALTER TABLE outbox_messages ADD COLUMN event_position bigint GENERATED BY DEFAULT AS IDENTITY;
-- Restore snapshot insertion order, independent of mutable available_at and IDs.
WITH source AS (
  SELECT message->>'id' AS id, ordinal FROM cvg_runtime_state,
    jsonb_array_elements(state->'outbox') WITH ORDINALITY AS messages(message, ordinal) WHERE cvg_runtime_state.id = 1
), ordered AS (
  SELECT message.id, row_number() OVER (ORDER BY source.ordinal NULLS LAST, message.event_position) AS position
    FROM outbox_messages message LEFT JOIN source USING (id)
)
UPDATE outbox_messages message SET event_position = ordered.position FROM ordered WHERE message.id = ordered.id;
SELECT setval(pg_get_serial_sequence('outbox_messages', 'event_position'), COALESCE(max(event_position), 1), count(*) > 0) FROM outbox_messages;
ALTER TABLE outbox_messages ADD CONSTRAINT outbox_messages_event_position_unique UNIQUE (event_position);
CREATE INDEX outbox_messages_replay_idx ON outbox_messages (event_position DESC) WHERE status IN ('PENDING', 'PROCESSED');
CREATE INDEX outbox_messages_claim_position_idx ON outbox_messages (event_position) WHERE status IN ('PENDING', 'PROCESSING');

UPDATE cvg_runtime_state SET state = jsonb_set(state, '{outbox}', '[]'::jsonb), version = version + 1, updated_at = now() WHERE id = 1;
ALTER TABLE cvg_runtime_state ADD CONSTRAINT runtime_outbox_is_transient CHECK (COALESCE(state->'outbox' = '[]'::jsonb, false));
UPDATE runtime_storage_boundaries SET projected_relations = ARRAY[]::text[] WHERE boundary_key = 'runtime-jsonb-snapshot-v1';
INSERT INTO runtime_storage_boundaries (boundary_key, authoritative_store, read_mode, write_mode, projected_relations, status, reconciliation_mode, contract_version)
VALUES ('outbox-messages-v1', 'outbox_messages', 'RELATIONAL', 'RELATIONAL', ARRAY[]::text[], 'RELATIONAL_READY', 'COMPLETE', 'OutboxMessage-v1');
UPDATE relational_schema_markers SET schema_version = '014_outbox_read_authority' WHERE marker_key = 'RELATIONAL_CLINICAL_CORE_EXPAND_V1';
