"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { ItemState, Priority } from "@cvg/contracts";
import { apiFetch, formatRelativeTime, getSafeErrorMessage } from "./api-client";
import { PriorityBadge, StatusBadge } from "./status-badge";
import { WorkflowAction } from "./workflow-action";

interface QueueItem { id: string; requestId: string; status: ItemState; workflowType: "LABORATORY" | "RADIOLOGY" | "ULTRASOUND"; priority: Priority; version: number; currentResultId?: string; currentSampleId?: string; procedureId?: string; procedureVersion?: number; dueAt: string; createdAt: string; requestCode: string; nextAction: string; overdue: boolean; patient: { displayName: string; species: string; externalId: string }; service: { name: string } }
export function QueueView() {
  const [items, setItems] = useState<QueueItem[]>([]); const [department, setDepartment] = useState("INPATIENT"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [overdue, setOverdue] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const me = await apiFetch<{ user: { role: string; departmentCode: string; managedDepartmentCodes?: string[] } }>("/session/me"); const departments = me.user.role === "MANAGER" ? Array.from(new Set([me.user.departmentCode, ...(me.user.managedDepartmentCodes ?? [])])) : [me.user.departmentCode]; setDepartment(departments.join(" · ")); const queueResults = await Promise.allSettled(departments.map((code) => apiFetch<QueueItem[]>(`/queues/${encodeURIComponent(code)}/items?${overdue ? "overdue=true" : ""}`))); const queues = queueResults.filter((result): result is PromiseFulfilledResult<QueueItem[]> => result.status === "fulfilled"); const failures = queueResults.filter((result) => result.status === "rejected"); if (queues.length === 0 && failures[0]?.status === "rejected") throw failures[0].reason; setItems(queues.flatMap((result) => result.value)); if (failures.length > 0) setError("Parte das filas está indisponível; os itens visíveis podem estar desatualizados."); } catch (cause) { setError(getSafeErrorMessage(cause, "Não foi possível carregar a fila.")); } finally { setLoading(false); } }, [overdue]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const refresh = () => { void load(); }; window.addEventListener("cvg:realtime-updated", refresh); window.addEventListener("cvg:realtime-resync", refresh); return () => { window.removeEventListener("cvg:realtime-updated", refresh); window.removeEventListener("cvg:realtime-resync", refresh); }; }, [load]);
  return <div className="queue-page"><div className="page-heading"><div><p className="eyebrow">Operação · {department}</p><h1>Central de <em>exames.</em></h1><p className="page-lede">A próxima ação de cada item, na ordem certa.</p></div><div className="queue-actions"><label className="toggle"><input type="checkbox" checked={overdue} onChange={(event) => setOverdue(event.target.checked)} /><span />Somente atrasados</label><button className="button button-ghost" onClick={() => void load()}>↻ Atualizar</button></div></div>{error && <div className="error-state" role="alert">{error}<button className="button button-ghost" onClick={() => void load()}>Tentar novamente</button></div>}<section className="panel queue-panel"><div className="queue-summary"><span><strong>{items.length}</strong> itens na fila</span><span className="queue-note">Ordenação: prioridade · prazo · espera</span></div>{loading ? <div className="queue-loading" role="status" aria-live="polite">Carregando fila…</div> : items.length === 0 ? <div className="empty-state"><span>✓</span><strong>Nenhum item nesta fila</strong><p>Novas solicitações aparecerão aqui quando estiverem no escopo do setor.</p></div> : <div className="queue-table-wrap"><table className="queue-table"><caption className="sr-only">Fila de exames</caption><thead><tr><th>Paciente</th><th>Exame</th><th>Prioridade</th><th>Status</th><th>Prazo</th><th>Próxima ação</th><th>Ação</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id} className={item.overdue ? "row-overdue" : ""}><td><Link href={`/requests/${item.requestId}`} className="table-patient"><strong>{item.patient.displayName}</strong><small>{item.patient.species} · {item.patient.externalId}</small></Link></td><td><strong>{item.service.name}</strong><small>{item.requestCode}</small></td><td><PriorityBadge priority={item.priority} /></td><td><StatusBadge status={item.status} /></td><td><span className={item.overdue ? "text-danger" : ""}>{item.overdue ? "Atrasado" : formatRelativeTime(item.dueAt)}</span></td><td><span className="next-action">{item.nextAction}</span></td><td><WorkflowAction item={item} onComplete={() => void load()} /></td><td><Link href={`/requests/${item.requestId}`} className="row-arrow" aria-label={`Abrir ${item.service.name}`}>→</Link></td></tr>)}</tbody></table></div>}</section></div>;
}
